version: '3'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
       POSTGRES_USER: ${POSTGRES_USER}
       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
       POSTGRES_DB: ${POSTGRES_DB_NAME}
       POSTGRES_PORT: ${POSTGRES_PORT}
    ports:
        - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
        - ./postgres-data:/var/lib/postgresql/data
  api:
    build: .
    command: uwsgi --ini config.ini
    restart: always
    volumes:
      - .:/c3po/
    ports:
      - "8000:8000"
    depends_on:
      - db
