version: "3.8"

services:
  postgresdb:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: lttkgp
      POSTGRES_PASSWORD: hellothere
      POSTGRES_DB: lttkgp
      POSTGRES_PORT: 5432
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - lttkgp-network
  c3po:
    build: .
    environment:
      FLASK_DEBUG: 1
    restart: always
    volumes:
      - .:/c3po/
      - ./entrypoint_dev.sh:/entrypoint.sh
    ports:
      - "8000:8000"
    networks:
      - lttkgp-network
    depends_on:
      - postgresdb

volumes:
  postgres_data:

networks:
  lttkgp-network:
    name: lttkgp-network
    driver: bridge
