version: 2.1

#########
# Common
#########
orbs:
  slack: circleci/slack@3.4.2


############
# Workflows
############
workflows:
  version: 2
  build-deploy:
    jobs:
      - build

##################
# Job Definitions
##################
jobs:
  build: &build-template
    docker:
      - image: circleci/python:3.6.2-stretch-browsers
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - restore_cache: 
          key: deps9-{{ .Branch }}-{{ checksum "requirements/common.txt" }}
      - run:
          command: |
            python -m venv env
            . env/bin/activate
            pip install -r requirements/common.txt
            pip install -r requirements/dev.txt
            pip install -e .
      - save_cache:
          key: deps9-{{ .Branch }}-{{ checksum "requirements/common.txt" }}
          paths:
            - ".env"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.6/site-packages"
      - run:
          command: |
            . env/bin/activate
            ./bin/sanity.sh 
      - slack/status:
          success_message: C-3PO built successfully
          failure_message: Build failed, check logs.