dist: xenial
language: python
python:
  - 3.6

env:
  - TESTING=True

# install the dependencies
install:
  - pip install -r requirements/common.txt
  - pip install -r requirements/dev.txt

script:
  - bash c3po/sanity.sh
